-- =====================================================================
-- Kasirnya POS — Supabase Schema (cerminan DB produksi `kasir-nya`)
-- Project ref: wnrlgduriwyeesxjlbrl
--
-- Multi-store: isolasi data antar toko via store_id (bigint FK ke stores.id),
-- ditegakkan di app layer (semua query .eq('store_id', storeId)).
-- RLS aktif di semua tabel dengan policy permissif.
--
-- Auth:
--   - Admin  → auth.users + public.profiles (role='admin')
--   - Kasir  → public.cashiers (email + password plaintext)
-- Provisioning manual via helper function create_admin() / create_cashier().
-- TIDAK ada self-registration.
-- =====================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ── 1. stores ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.stores (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    code        TEXT UNIQUE,
    avatar_url  TEXT,
    created_at  TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- ── 2. profiles (admin; 1:1 dengan auth.users) ───────────────────────
CREATE TABLE IF NOT EXISTS public.profiles (
    id          UUID PRIMARY KEY REFERENCES auth.users(id),
    email       TEXT,
    role        TEXT CHECK (role IN ('admin', 'cashier')),
    store_id    BIGINT REFERENCES public.stores(id),
    created_at  TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- ── 3. cashiers (kasir; auth via lookup email+password) ──────────────
CREATE TABLE IF NOT EXISTS public.cashiers (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name        TEXT NOT NULL,
    email       TEXT NOT NULL UNIQUE,
    password    TEXT NOT NULL,
    store_id    BIGINT NOT NULL REFERENCES public.stores(id),
    created_at  TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- ── 4. categories ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.categories (
    id          TEXT PRIMARY KEY DEFAULT (gen_random_uuid())::text,
    name        TEXT NOT NULL,
    emoji       TEXT DEFAULT '📦',
    store_id    BIGINT NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT now()
);

-- ── 5. products ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.products (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name            TEXT NOT NULL,
    description     TEXT,
    price           NUMERIC NOT NULL,
    image_url       TEXT,
    category        TEXT NOT NULL,
    stock_status    TEXT NOT NULL,
    stock_quantity  INTEGER NOT NULL DEFAULT 0,
    store_id        BIGINT NOT NULL REFERENCES public.stores(id),
    created_at      TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- ── 6. transactions ──────────────────────────────────────────────────
-- total_amount = grand total (sudah termasuk PPN 11%). Subtotal di-derive
-- ulang saat display (grand / 1.11). Metode bayar HANYA 'Cash' & 'QRIS'.
CREATE TABLE IF NOT EXISTS public.transactions (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id        TEXT NOT NULL,
    customer_name   TEXT NOT NULL,
    customer_email  TEXT,
    cashier_name    TEXT,
    total_amount    NUMERIC NOT NULL,
    payment_method  TEXT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'Success',
    items           JSONB NOT NULL,
    store_id        BIGINT NOT NULL REFERENCES public.stores(id),
    created_at      TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- =====================================================================
-- Row Level Security — semua tabel ON, policy permissif (isolasi di app)
-- =====================================================================
ALTER TABLE public.stores       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cashiers     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow_all" ON public.stores       FOR ALL USING (true);
CREATE POLICY "allow_all" ON public.categories   FOR ALL USING (true);
CREATE POLICY "allow_all" ON public.products     FOR ALL USING (true);
CREATE POLICY "allow_all" ON public.transactions FOR ALL USING (true);

CREATE POLICY "Allow public read access to profiles" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Allow users to update their own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Allow system/insert on profiles" ON public.profiles FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow select on cashiers" ON public.cashiers FOR SELECT USING (true);
CREATE POLICY "Allow admin to manage cashiers" ON public.cashiers FOR ALL USING (true);

-- =====================================================================
-- Trigger: auto-bikin profile tiap ada user baru di auth.users
-- (default role='admin', store_id=1 → di-update oleh create_admin)
-- =====================================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, role, store_id)
  VALUES (NEW.id, NEW.email, 'admin', 1);
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- =====================================================================
-- Helper functions (SECURITY DEFINER, server-only)
-- Provisioning manual akun — TIDAK bisa dipanggil dari client app.
--   SELECT public.create_admin('owner@toko.com', 2);
--   SELECT public.create_cashier('Budi', 'budi@toko.com', 2);
-- Password default: admin = 'admin123', kasir = 'kasir123'.
-- =====================================================================
CREATE OR REPLACE FUNCTION public.create_admin(p_email text, p_store_id bigint)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  new_user_id uuid;
BEGIN
  new_user_id := gen_random_uuid();

  INSERT INTO auth.users (
    instance_id, id, aud, role, email,
    encrypted_password, email_confirmed_at,
    raw_app_meta_data, raw_user_meta_data,
    created_at, updated_at, confirmation_token,
    email_change, email_change_token_new, recovery_token
  ) VALUES (
    '00000000-0000-0000-0000-000000000000',
    new_user_id, 'authenticated', 'authenticated',
    lower(trim(p_email)),
    crypt('admin123', gen_salt('bf')),
    now(),
    '{"provider":"email","providers":["email"]}'::jsonb,
    '{}'::jsonb,
    now(), now(), '', '', '', ''
  );

  INSERT INTO auth.identities (
    id, user_id, identity_data, provider, provider_id,
    last_sign_in_at, created_at, updated_at
  ) VALUES (
    gen_random_uuid(), new_user_id,
    jsonb_build_object('sub', new_user_id::text, 'email', lower(trim(p_email))),
    'email', new_user_id::text,
    now(), now(), now()
  );

  -- Trigger on_auth_user_created udah auto-insert ke profiles dengan store_id=1
  UPDATE public.profiles SET store_id = p_store_id WHERE id = new_user_id;

  RETURN new_user_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.create_cashier(p_name text, p_email text, p_store_id bigint)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  new_cashier_id uuid;
BEGIN
  INSERT INTO public.cashiers (name, email, password, store_id)
  VALUES (p_name, lower(trim(p_email)), 'kasir123', p_store_id)
  RETURNING id INTO new_cashier_id;

  RETURN new_cashier_id;
END;
$$;

-- =====================================================================
-- GETTING STARTED — isi sendiri sesuai tokomu
-- ---------------------------------------------------------------------
-- Habis jalanin script di atas, DB masih KOSONG (belum ada toko/akun/
-- produk). Ikutin langkah ini biar bisa langsung login & coba aplikasi.
-- Uncomment + ganti nilainya, jalanin di SQL Editor.
--
--   1) Bikin toko (catat id-nya buat langkah berikutnya):
-- INSERT INTO public.stores (name, code) VALUES ('Toko Demo', 'demo')
-- RETURNING id;
--
--   2) Bikin akun admin (login default password: admin123):
--      ganti <STORE_ID> dengan id dari langkah 1.
-- SELECT public.create_admin('admin@demo.com', <STORE_ID>);
--
--   3) (opsional) Bikin akun kasir (login default password: kasir123):
-- SELECT public.create_cashier('Budi', 'budi@demo.com', <STORE_ID>);
--
--   4) (opsional) Isi kategori — store_id = <STORE_ID>:
-- INSERT INTO public.categories (name, emoji, store_id) VALUES
--   ('Kopi',    '☕', <STORE_ID>),
--   ('Non-Kopi','🍵', <STORE_ID>),
--   ('Makanan', '🍚', <STORE_ID>);
--
--   5) (opsional) Isi produk — harga dalam Rupiah (angka polos, tanpa titik):
-- INSERT INTO public.products
--   (name, description, price, category, stock_status, stock_quantity, store_id) VALUES
--   ('Kopi Susu Gula Aren', 'Espresso + susu + gula aren', 22000, 'Kopi', 'In Stock', 50, <STORE_ID>),
--   ('Americano',           'Espresso + air',             18000, 'Kopi', 'In Stock', 50, <STORE_ID>);
--
--   ⚠️ Catatan penting:
--   - Produk & kategori juga bisa diisi langsung dari menu Catalog di app
--     (lebih gampang, gak perlu SQL).
--   - Metode bayar HANYA 'Cash' & 'QRIS' — jangan tambah Debit/Kredit.
--   - total_amount di transaksi = grand total (sudah termasuk PPN 11%).
--   - Ganti password default: admin lewat "Lupa kata sandi" di app,
--     kasir lewat UPDATE public.cashiers SET password='...' WHERE email='...'.
-- =====================================================================
